### ISSUE TITLE
subsonic Rockon container last update 5 yrs ago

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#316] opened 2022-05-21 15:28 UTC
subsonic.json - the underlying container was last updated 5 years ago. This image could possibly replaced with the one found here https://hub.docker.com/r/hydria/subsonic/ that seems more active.

**Comment by Hooverdan96** [comment] 2022-05-22 19:31
@JasonTarka, are you still using the subsonic docker image? Or have you switched to a newer one that we could use for the Rockon?

**Comment by FroggyFlox** [comment] 2022-05-22 20:27
@Hooverdan96 , @phillxnet ,

The Arch Wiki lists Subsonic as no longer maintained and the last changelog on Aubsonic's website dates from 2019!
"Subsonic" http://www.subsonic.org/pages/changelog.jsp

We might want to deprecate this Rock-ok too...

**Comment by Hooverdan96** [comment] 2022-05-22 22:35
Probably a good idea.
From what I read, Subsonic went closed code end of 2016 and only had a couple of additional releases since then, there seemed to have open source continuations like libresonic and then airsonic (also not maintained anymore). From airsonic there was another fork airsonic-advance. That could be the alternative (https://github.com/airsonic-advanced/airsonic-advanced), it has reasonable activity in terms of commits (last one merged in April), their last stable release is from 2020 but they have been pre-releasing snapshots very frequently.
But, in short, agree that subsonic should be removed, unless there's a user base out there in the Rockstor community.

**Comment by Hooverdan96** [comment] 2022-05-22 22:42
I just realized, the we had some conversation not too long ago here: #307 
And discussed airsonic as an alternative (which would now apply to going to airsonic-advanced, I guess).

**Comment by phillxnet** [comment] 2022-09-24 16:07
@Hooverdan96 Yes, just doing some tidy now and @Termitebug is again active on the linked issue.
I'll close this as part of my ongoing clean up via #335 and as

Duplicate of more currently active #307 

Thanks for the house keeping done here to date.

**Closed by phillxnet** 2022-09-24 16:07 UTC
