### ISSUE TITLE
Container command and argument options

### ISSUE THREAD

**Issue by renatoornelas** [rockstor/rockon-registry#71] opened 2017-01-18 19:10 UTC
Hi,

I'm building a minio (http://minio.io) rockon, but the minio image requires a command and a argument in the docker run invocation (server /export).

But I didn't see a place to put this info on rockon json file.

BTW, I fixed by editing the container config.json and adjusting the Arg and Cmd parameters. After restarting the rockon service, everything is running fine.

**Comment by phillxnet** [comment] 2019-02-03 13:10
@renatoornelas Just doing some tidy here in our old issues. Thanks for the feedback. We may now have a new capability that relates to your prior requirement.

@FroggyFlox Does your recently added:
"Add Support for Docker run command arguments. Fixes #1967" #1968
relate to @renatoornelas's prior circumstance.

In which case we can note this and close this issue as a result.

**Comment by FroggyFlox** [comment] 2019-02-03 13:42
> @FroggyFlox Does your recently added:
> "Add Support for Docker run command arguments. Fixes #1967" #1968
> relate to @renatoornelas's prior circumstance.

Yes, it should address exactly that. Thanks a lot for bringing this up!

@renatoornelas, if it still is relevant, maybe you could give it a try and confirm it is working as intended?

**Comment by MikeMcPherson** [comment] 2020-07-18 14:52
I have a Minio Rock-on working and would like to submit it.  Should I piggyback on this issue or start a new one?  Thanks!

**Comment by FroggyFlox** [comment] 2020-07-18 15:36
> I have a Minio Rock-on working and would like to submit it. Should I piggyback on this issue or start a new one? Thanks!

Hi @MikeMcPherson ,

Thanks a lot for willing to share your rock-on! Personally, I would recommend creating a new issue for it as this one was mostly related to command arguments and not Minio-specific; this would thus help keep things tidy. Feel free to link to this one if you'd like to keep things connected.

Thanks again and let us know if there's any other question you may have. We tried to make the PR template as helpful as possible but let us know if there's anything unclear about it so that we can improve where needed.

Best,

**Comment by Hooverdan96** [comment] 2023-12-19 17:13
As the Minio Rockon has been added via #232, closing this as completed

**Closed by Hooverdan96** 2023-12-19 17:13 UTC
