### ISSUE TITLE
Unmaintained and outdated duplicati?

### ISSUE THREAD

**Issue by HBDK** [rockstor/rockon-registry#206] opened 2019-11-27 20:12 UTC
So i have had some issues with the duplicati contianer and went to check on it on [docker hub](https://hub.docker.com/r/intersoftlab/duplicati/dockerfile) and [github](https://github.com/dmitryint/docker-duplicati) and it looks pretty dead.

maybee you should consider replacing it with one from linuxserver.io

**Comment by FroggyFlox** [comment] 2019-11-28 02:34
Thanks @HBDK for bringing the attention on this one; I agree with you that it needs to be updated given it hasn't been updated since at least a year ago.

Regarding replacement, your recommendation of the Linuxserver.io image seems the best to me as well. There seems to be an official image (https://hub.docker.com/r/duplicati/duplicati) but not as popular as the Linuxserver.io one. Here are the numbers:

| Image | Stars | Pulls | last updated | latest duplicati version available |
| ---- | ---- | ---- | ---- | ---- |
| duplicati/duplicati | 23 | 1M+ | 23 days ago | 2.0.4.34-canary_2019-11-05 |
| linuxserver/duplicati | 112 | 10M+ | 6 days ago | 2.0.4.23-canary_2019-07-14 |

Both images seem to provide similar options for configuration, but the linuxserver.io one does bring their usual PUID and PGID for user and group specification, which can help prevent user permissions issues. I do not know whether this is a problem for Duplicati, however, so it may be a moot point.

@HBDK, have you tested any of these two images already? The official images are usually preferred as they tend to come with better assurances that the image will be maintained and up-to-date, but the Linuxserver.io ones are usually rather well maintained too so I would tend to believe it would all depend on difference(s) between the two images from a user perspective.

Thanks for any feedback you may have; I'll try to make an update as soon as possible as it seems rather straightforward. It would be great if you would be willing to test any update and see whether it fixes your problem(s).

Cheers,

**Comment by FroggyFlox** [comment] 2019-11-28 03:42
@HBDK, as mentioned above, I've quickly put up together a rock-on based on the official image. Feel free to give it a test and see if it fixes your issue(s) and whether it works as intended. You can find it below:
https://raw.githubusercontent.com/FroggyFlox/rockon-registry/26bb179792704815ed95820f9ef0fb27cc269a0f/duplicati2-canary-official.json

Hope this helps,

**Comment by HBDK** [comment] 2019-11-28 06:20
Just looking at the json I will have to say that that is not a suitable replacement, you would need to map a folder to /config instead of data.  
I would rather not switch my own duplicati back to a rock-on (switched to docker compose right before I opened this issue) but I might be able to find time to make a test in a VM and make a pull request with a suitable json file.

**Comment by HBDK** [comment] 2019-11-28 06:22
Sorry disregard my comment about the file you provided I assumed it was the linuxserver io image not the official image.

**Comment by FroggyFlox** [comment] 2019-11-29 14:26
No worries, @HBDK. I hope your issue(s) with it are now fixed. Are you using the Linuxserver.io image, and are you happy with it?

Would you have, by any chance, some feedback on the stability of the _canary_ vs _beta_ releases? Our current rock-on was targeting canary releases, but the beta ones are (understandably) recommended by their image's documentation so I was curious in case you had tried both of those.

**Comment by HBDK** [comment] 2019-11-30 08:38
i think they will be, one of the issues i have had with the old contianer was that it was updated inside the contianer, so if you for some reason had to recreate the contianer you would get an old version of the software that was unable to read the config db and therfor not start, but that doesn't seem to be an issue with the linuxserver.io image.  
  
that being said the old also stored the config in /root/.config so i'm a bit worried that et might run as root wich as far as i know i very bad for contianers(or any thing else) to do!  
  
i how ever discovered a minor issue when shifting to a new container, each backup has its own db file and the main config db contains a path for each of these, so you have to manually change that path for each backup. it is done in database under advance.

![image](https://user-images.githubusercontent.com/1486019/69898118-17c29f00-1355-11ea-898e-6270e0733954.png)

**Comment by FroggyFlox** [comment] 2019-11-30 15:24
> i think they will be, one of the issues i have had with the old contianer was that it was updated inside the contianer, so if you for some reason had to recreate the contianer you would get an old version of the software that was unable to read the config db and therfor not start, but that doesn't seem to be an issue with the linuxserver.io image.

Thanks for pointing it out... we may want to detail in the `"more_info"` field the recommended update procedure in this case (not using Duplicati UI, but proceed with Uninstall > Re-install rock-on).



> that being said the old also stored the config in /root/.config so i'm a bit worried that et might run as root wich as far as i know i very bad for contianers(or any thing else) to do!

Agreed. That's why I tend to like the Linuxserver.io images... @phillxnet, I'll probably switch from the official to the Linuxserver.io image as they both offer the same versions and features, but the Linuxserver.io one does allow for setting a specific user under which to run the container.



> i how ever discovered a minor issue when shifting to a new container, each backup has its own db file and the main config db contains a path for each of these, so you have to manually change that path for each backup. it is done in database under advance.

Thanks a lot for pointing this out as well, @HBDK! I tried to find clear instructions from Duplicati on how to migrate but failed to find reliable and clear information. Your feedback is then extremely valuable so thanks a lot! I'll give a try myself at migrating between our current rock-on and the new one and report back.

Thanks again!

**Comment by FroggyFlox** [comment] 2019-11-30 16:22
After a quick test, it appears the Linuxserver.io is our best choice:
1. Install our current Duplicati rock-on
2. Set a new backup to Google Drive
3. Run the backup once
4. Turn rock-on off
5. Install the Duplicati rock-on using the Linuxserver.io image, and using the same share used in step 1
6. The backup create in step 2 above was automatically detected and available.
7. Change the database path to `/config/<databasename>.sqlite
8. New backup works.

In contrast, installing the official Duplicati rock-on using the same share used in step 1 above does not lead to the test backup set in step 2 to be detected automatically. It would thus require the user to re-create all backups manually.

I'll thus proceed with finalizing the rock-on using the Linuxserver.io.

**Comment by HBDK** [comment] 2019-11-30 17:30
Cool! by the way on the Canary vs beta thing, i think we should stick with beta (i think it is default in the linuxserver.io image) since as far as i can tell canary is only for development.

it might also be a good idea to add a short description on how to map shares into this container as well since that is probably going to be relevant for most people who would like to use this container.
i personally have mine mapped to /<sharename> but there might be a better place to map them inside the container.

**Comment by FroggyFlox** [comment] 2019-12-01 04:13
@HBDK, I've now created a PR using the Linuxserver.io image: #207.

Feel free to have a look and test if you'd like, it would be much appreciated!

Thanks again for bringing attention to this.

**Closed** 2019-12-02 11:08 UTC

**Comment by phillxnet** [comment] 2019-12-02 12:02
@HBDK @FroggyFlox Just noting here for convenience that @FroggyFlox's pull request has now been merged and published.

We can see how this beta offering goes and hopefully move over to a stable offering once that become viable.

Thanks to both of you for your efforts on this one. Duplicati looks like an excellent application in our context and it's good to have moved this over to our newer format and a newer linuxserver.io sourced image.
